package com.app2.model;

import java.time.LocalDate;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;


@Entity
public class Flat {
	
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int FlatId; //autogenerated
	private String BuildingName;
	private int  NoOfRooms;//(add validation no should be less than 10)
   private	LocalDate date_of_manufacturing;// LocalDate (JSON Format)
             private   Facing facing;//(East, West, Nort, South)
             private int price;
             private String description;
             
             
			public int getFlatId() {
				return FlatId;
			}
			
			public void setFlatId(int flatId) {
				FlatId = flatId;
			}
			
			public String getBuildingName() {
				return BuildingName;
			}
			
			public void setBuildingName(String buildingName) {
				BuildingName = buildingName;
			}
			public int getNoOfRooms() {
				return NoOfRooms;
			}
			public void setNoOfRooms(int noOfRooms) {
				NoOfRooms = noOfRooms;
			}
			public LocalDate getDate_of_manufacturing() {
				return date_of_manufacturing;
			}
			public void setDate_of_manufacturing(LocalDate date_of_manufacturing) {
				this.date_of_manufacturing = date_of_manufacturing;
			}
			public Facing getFacing() {
				return facing;
			}
			public void setFacing(Facing facing) {
				this.facing = facing;
			}
			public int getPrice() {
				return price;
			}
			public void setPrice(int price) {
				this.price = price;
			}
			public String getDescription() {
				return description;
			}
			public void setDescription(String description) {
				this.description = description;
			}
			
			
			
			
			@Override
			public String toString() {
				return "Flat [FlatId=" + FlatId + ", BuildingName=" + BuildingName + ", NoOfRooms=" + NoOfRooms
						+ ", date_of_manufacturing=" + date_of_manufacturing + ", facing=" + facing + ", price=" + price
						+ ", description=" + description + "]";
			}
             
             

}
